PR-1 Create Codebase
artmnzn/perfumes-site pull request #1
Opened 2023-12-17 03:24 UTC by artmnzn

code generated by Gatsby to initiate the project

2023-12-17 03:29 UTC, diedu89 requested changes
We're missing eslint and prettier config

2023-12-17 03:29 UTC, diedu89 commented on tailwind.config.js
remove this config file, it should be part of PR-2

2023-12-17 03:29 UTC, diedu89 commented on package.json
> +    "tailwindcss": "^3.3.6"
let's remove this and work on it in PR-2

2023-12-17 03:29 UTC, diedu89 commented on src/styles/global.css
part of PR-2

2023-12-17 03:29 UTC, diedu89 commented on postcss.config.js
same, another tailwind config

2023-12-17 03:29 UTC, diedu89 commented on gatsby-browser.js
also tailwind related

2023-12-17 03:38 UTC, artmnzn commented
@diedu89 When created codebase Gatsby allowed me to choose tailwind style engine

2023-12-17 03:40 UTC, diedu89 approved these changes
never mind LGTM if gatsby was able to add it within the defaults

2023-12-17 03:42 UTC, diedu89 commented
sorry I forgot we're still missing eslint and prettier config

2023-12-21 22:51 UTC, diedu89 approved these changes
eslint and prettier will be configured on other ticket

2023-12-21 22:55 UTC, merged